# dpl v2
# https://docs.travis-ci.com/user/deployment-v2

language: node_js

node_js:
  - lts/*

branches:
  only:
    - master

before_install:
  - npm link

install:
  - npm ci
  - npm link @ttionya/travisci-test

script:
  - npm run test

cache:
  directories:
    - '$HOME/.npm'
